# lab.nix — pure NixOS module, layered on top of your existing configuration.
# No stateVersion, no networking.hostName — those already live in
# /etc/nixos/configuration.nix.

{ config, pkgs, lib, ... }:

let
  # ── Addresses & ports ────────────────────────────────────────────────────────
  giteaHost = "localhost";
  giteaPort = 3000;
  wpPort    = 8000;
  wpGrpc    = 9000;          # internal communication: server ↔ agent
  giteaUrl  = "http://${giteaHost}:${toString giteaPort}";
  wpUrl     = "http://${giteaHost}:${toString wpPort}";

  # ── Secrets ──────────────────────────────────────────────────────────────────
  # For a local lab, plain strings are fine.
  # For production use, consider sops-nix or agenix.
  wpAgentSecret = "change-me-agent-secret";

  # These two values are generated by Gitea after the first login.
  # Fill them in after the OAuth2 step (see README) and run nixos-rebuild again.
  wpOauthClientId     = "FILL_AFTER_GITEA_OAUTH2_SETUP";
  wpOauthClientSecret = "FILL_AFTER_GITEA_OAUTH2_SETUP";
in
{
  # ── Firewall ──────────────────────────────────────────────────────────────────
  networking.firewall.allowedTCPPorts = [ giteaPort wpPort ];
  # wpGrpc (9000) is internal only — no need to open it on the firewall

  # ── Useful packages ───────────────────────────────────────────────────────────
  environment.systemPackages = with pkgs; [
    git
    curl
    jq
    woodpecker-cli   # CLI to interact with Woodpecker
  ];

  # ── PostgreSQL ────────────────────────────────────────────────────────────────
  # If services.postgresql is already defined in your configuration.nix,
  # NixOS merges the attributes — ensureDatabases and ensureUsers accumulate
  # without conflict.
  services.postgresql = {
    enable  = true;
    package = pkgs.postgresql_17;

    ensureDatabases = [ "gitea" "woodpecker" ];
    ensureUsers = [
      { name = "gitea";      ensureDBOwnership = true; }
      { name = "woodpecker"; ensureDBOwnership = true; }
    ];
  };

  # ── Gitea ─────────────────────────────────────────────────────────────────────
  services.gitea = {
    enable   = true;
    package  = pkgs.gitea;
    appName  = "Lab Gitea";

    database = {
      type   = "postgres";
      name   = "gitea";
      user   = "gitea";
      socket = "/run/postgresql";   # peer auth — no password needed
    };

    settings = {
      server = {
        HTTP_PORT    = giteaPort;
        ROOT_URL     = "${giteaUrl}/";
        DOMAIN       = giteaHost;
        OFFLINE_MODE = true;
      };
      service = {
        DISABLE_REGISTRATION       = false;   # set to true after creating the admin account
        REQUIRE_SIGNIN_VIEW        = false;
        DEFAULT_KEEP_EMAIL_PRIVATE = true;
      };
      oauth2 = {
        ENABLED    = true;
        # JWT_SECRET = "change-me-jwt-secret";
        # Generate a proper value with: gitea generate secret JWT_SECRET
      };
      log.LEVEL = "Info";
    };
  };

  systemd.services.gitea = {
    after    = [ "postgresql.service" ];
    requires = [ "postgresql.service" ];
  };

  # ── Woodpecker Server ─────────────────────────────────────────────────────────
  services.woodpecker-server = {
    enable = true;

    environment = {
      WOODPECKER_HOST        = wpUrl;
      WOODPECKER_SERVER_ADDR = ":${toString wpPort}";
      WOODPECKER_GRPC_ADDR   = ":${toString wpGrpc}";

      # SCM: Gitea
      WOODPECKER_GITEA        = "true";
      WOODPECKER_GITEA_URL    = giteaUrl;
      WOODPECKER_GITEA_CLIENT = wpOauthClientId;

      # Access control
      WOODPECKER_ADMIN = "admin";   # your Gitea username
      WOODPECKER_OPEN  = "true";    # all Gitea users can log in

      # Database
      WOODPECKER_DATABASE_DRIVER     = "postgres";
      WOODPECKER_DATABASE_DATASOURCE = "host=/run/postgresql dbname=woodpecker user=woodpecker sslmode=disable";
    };

    # Sensitive secrets in a separate file (ideally kept outside /nix/store)
    environmentFile = pkgs.writeText "woodpecker-server-secrets" ''
      WOODPECKER_AGENT_SECRET=${wpAgentSecret}
      WOODPECKER_GITEA_SECRET=${wpOauthClientSecret}
    '';
  };

  systemd.services.woodpecker-server = {
    after    = [ "gitea.service" "postgresql.service" ];
    requires = [ "postgresql.service" ];
  };

  # ── Woodpecker Agent ──────────────────────────────────────────────────────────
  services.woodpecker-agents.agents.local = {
    enable = true;

    environment = {
      WOODPECKER_SERVER        = "localhost:9000";
      WOODPECKER_MAX_WORKFLOWS = "4";
      WOODPECKER_BACKEND       = "local";
    };

    environmentFile = [ (pkgs.writeText "woodpecker-agent-secrets" ''
      WOODPECKER_AGENT_SECRET=${wpAgentSecret}
    '') ];
  };

  systemd.services.woodpecker-agent-local = {
    after    = [ "woodpecker-server.service" ];
    requires = [ "woodpecker-server.service" ];
  };
}